name = "glason"
version = "0.1.0"
description = "A Gleam JSON library inspired by Elixir's Jason"
licenses = ["Apache-2.0"]
repository = { type = "github", user = "iainh", repo = "glason" }
targets = ["erlang"]

documentation = { title = "Glason" }

[dependencies]
gleam_stdlib = "~> 0.33.0"

[dev-dependencies]
gleeunit = "~> 1.2"
